base:
  fps: 2
  gray_scale: True
  num_concat_image: 4
  max_episode_length: 1000
  wait_time: 60.0
  state:
    image:
      dim: !!seq
        - 4 # equal to num_concat_image * (1 if gray_scale else 3)
        - 112
        - 112
      type: np.uint8
      norm: 255.
#    speed:
#      dim: !!seq
#        - 1
#      type: np.uint8
#      norm: 100.
  action:
    dim: 1
    type: np.int64
    head: 4
  reward:
    dim: 1
    type: np.float32
  done:
    dim: 1
    type: np.bool_
train:
  name: exp1
  lr: 0.00025
  batch_size: 256
  epsilon: 0.8
  epsilon_min: 0.1
  epsilon_steps: !!float 1.0e5
  gamma: 0.99
  warmup_steps: 5000
  buffer_size: !!float 1.0e5
  update_interval: 5
  target_update_interval: 100
  gradient_steps: 50
  reward_deque_length: 1000


