base:
  fps: 2
  gray_scale: False
  num_concat_image: 1
  max_episode_length: 1000
  wait_time: 60.0
  client_warmup_steps: 5000
  policy: SAC
  env: WRCGContinuousEnv
  state:
    image:
      dim: !!seq
        - 3 # equal to num_concat_image * (1 if gray_scale else 3)
        - 112
        - 112
      type: np.uint8
      norm: 255.
    speed:
      dim: !!seq
        - 1
      type: np.uint8
      norm: 100.
  action:
    dim: 2
    type: np.int64
    head: 2
    spaces: !!seq
      - 'w'
      - 'a'
      - 'd'
  reward:
    dim: 1
    type: np.float32
  done:
    dim: 1
    type: np.bool_
train:
  name: exp1_sac
  lr: !!float 7.3e-4
  batch_size: 256
  gamma: 0.99
  warmup_steps: 5000
  buffer_size: !!float 2.0e5
  update_interval: 5
  save_interval: 100
  gradient_steps: 50
  reward_deque_length: 1000
  tau: 0.02


